config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root 'posts#index'
  devise_scope :user do
  get 'login', to: 'devise/sessions#new'

end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<nav class="navbar navbar-default" role="navigation">
  <%= link_to 'Mój Blog', root_path, class: 'navbar-brand' %>
  <div class="container d-flex justify-content-end">
    <p class="navbar-text navbar-right">
      <% if user_signed_in? %>
      <%= link_to 'Nowy Post', new_post_path, class: 'navbar-link' %>
      <%= link_to 'Edycja Profilu', edit_user_registration_path, class: 'navbar-link' %>
      <% else %>
      <%= link_to 'Logowanie admina', new_user_session_path, class: 'navbar-link'%>
      <% end %>
    </p>
  </div>
</nav>
  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Tytuł %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :treść %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>




    <% @posts.each do |post| %>
        <h1><%= link_to post.title, post %></h1>
        <p align="right">Dodano <%= time_ago_in_words(post.created_at) %> temu</p>
       <hr>
  <% end %>
  <br>

app/views/posts/new.html.erb
<h1>Nowy Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h2>
  <%= @post.title %></h2>

</div>
  <div class="panel panel-default">
    <div class="panel-heading">
<h4 align='center'>
  <%= @post.body %>
</h4>
</div>
</div>

<% if user_signed_in? %>
<div class="btn-group pull-right d-flex justify-content-end">
   	<div class="btn-group ">
   		<%= link_to 'Edytuj', edit_post_path(@post), class: "btn btn-primary" %>
   		<%= link_to 'Usuń', @post, method: :delete, data: { confirm: 'Jesteś Pewien?' }, class: "btn btn-warning" %>
   	</div>
  </div>
<% end %>
<%= social_share_button_tag(@post.title) %>